spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://81.68.207.20:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 81.68.207.20:8848
  application:
    name: mall-product
# MapperScan
mybatis-plus:
  # sql映射文件位置
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      # entity主键自增
      id-type: auto
server:
  port: 10000