spring:
  application:
    name: mall-search
  cloud:
    nacos:
      discovery:
        server-addr: 81.68.207.20:8848
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 12000

logging:
  level:
    com.tech.gulimall: debug